#!/usr/bin/env python3
"""
Test Photo Caption Search in Pinecone
Simple script to test semantic search of photo captions.

USAGE:
======
python test_photo_search.py "happy moments"
python test_photo_search.py "winter day"
python test_photo_search.py "silly Ada"
"""

import os
import sys
import json
from pinecone import Pinecone
from dotenv import load_dotenv

def search_photo_captions(query_text, limit=5):
    """
    Search for photo captions similar to the query text
    
    Args:
        query_text: The text to search for
        limit: Maximum number of results to return
    
    Returns:
        List of matching photo captions with metadata
    """
    # Load environment variables
    load_dotenv()
    
    # Initialize Pinecone
    api_key = os.getenv("PINECONE_API_KEY")
    if not api_key:
        raise ValueError("PINECONE_API_KEY not found in environment variables")
    
    pc = Pinecone(api_key=api_key)
    
    # Generate embedding for the query
    print(f"🔍 Searching for: '{query_text}'")
    print("Generating query embedding...")
    
    query_embedding = pc.inference.embed(
        model="llama-text-embed-v2",
        inputs=[query_text],
        parameters={"input_type": "query"}
    )
    
    # Extract vector values
    if hasattr(query_embedding[0], 'values'):
        query_vector = query_embedding[0].values
    else:
        query_vector = query_embedding[0]
    
    print(f"Query vector dimension: {len(query_vector)}")
    
    # Search Pinecone photo-captions namespace
    index = pc.Index("adas-memory-qa-poc")
    
    results = index.query(
        vector=query_vector,
        top_k=limit,
        include_metadata=True,
        namespace="photo-captions"  # Search only photo captions
    )
    
    return results.matches

def display_results(matches, query_text):
    """Display search results in a readable format"""
    
    print("\n" + "=" * 80)
    print(f"PHOTO SEARCH RESULTS FOR: '{query_text}'")
    print("=" * 80)
    
    if not matches:
        print("❌ No matches found")
        return
    
    for i, match in enumerate(matches):
        print(f"\n{i+1}. MATCH (Score: {match.score:.4f})")
        print("-" * 40)
        
        metadata = match.metadata
        
        # Display caption and prompt type
        caption = metadata.get('caption_text', 'No caption')
        prompt_type = metadata.get('prompt_type', 'Unknown')
        print(f"📝 Caption ({prompt_type}): {caption}")
        
        # Display photo info
        filename = metadata.get('original_filename', 'Unknown')
        photo_date = metadata.get('photo_date', 'Unknown')
        ada_age = metadata.get('ada_age', 'Unknown')
        
        print(f"📷 Photo: {filename}")
        print(f"📅 Date: {photo_date}")
        print(f"👶 Ada's age: {ada_age} years" if ada_age != 'Unknown' else "👶 Ada's age: Unknown")
        
        # Display URLs
        wordpress_url = metadata.get('wordpress_url')
        thumbnail_url = metadata.get('wordpress_thumbnail')
        
        if wordpress_url:
            print(f"🔗 Full image: {wordpress_url}")
        if thumbnail_url:
            print(f"🖼️  Thumbnail: {thumbnail_url}")
        
        # Display generation info
        model_used = metadata.get('model_used', 'Unknown')
        record_hash = metadata.get('record_hash', 'Unknown')
        print(f"🤖 Generated by: {model_used}")
        print(f"🔍 Record ID: {match.id}")

def main():
    """Main function"""
    
    # Get query from command line or prompt user
    if len(sys.argv) > 1:
        query_text = " ".join(sys.argv[1:])
    else:
        query_text = input("Enter your search query: ").strip()
    
    if not query_text:
        print("❌ Please provide a search query")
        return
    
    try:
        # Search for photos
        matches = search_photo_captions(query_text, limit=3)
        
        # Display results
        display_results(matches, query_text)
        
        print("\n" + "=" * 80)
        print("✅ Search complete!")
        print("\nTry searching for:")
        print("  • Emotions: 'happy', 'joy', 'peaceful', 'silly'")
        print("  • Activities: 'playing', 'reading', 'hospital', 'family time'")
        print("  • Settings: 'winter', 'outdoors', 'home', 'medical'")
        print("  • Relationships: 'with family', 'sibling', 'parents'")
        print("=" * 80)
        
    except Exception as e:
        print(f"❌ Error during search: {e}")

if __name__ == '__main__':
    main()